### ISSUE TITLE
Main server app

### ISSUE THREAD

**Issue by Alessandro-Gobbetti** [AlbertCerfeda/sa3-final-project#6]

**Comment by AlbertCerfeda** [comment]
@Alessandro-Gobbetti 
if possible add the folder ```db/``` containing the database with the two empty collections ``` users``` and ```docs ```

**Comment by Alessandro-Gobbetti** [comment]
@AlbertCerfeda 
I'm not getting your point. MongoDB stores the collections in the location indicated in `/etc/mongodb.conf `: the default is `/var/lib/mongodb/`. Since we are connecting to mongodb server on localhost, each machine will have its own database. Do you want to change the location of the db? (Why, since it will still be local?)

I can add a little script to clear the database...
